artifacts_root: artifacts

data_ingestion:
  root_dir: artifacts/data_ingestion
  tickers: ["AAPL", "GOOG", "MSFT", "AMZN"]  # List of tickers
  start_date: 2012-01-01       # Start date for stock price data retrieval
  end_date: now                # End date for stock price data retrieval ('now' for current date)
  local_data_dir: artifacts/data_ingestion/raw_data  # Directory to save raw data files for each stock

data_transformation:
  root_dir: artifacts/data_transformation
  apple_data_dir: artifacts/data_ingestion/raw_data/AAPL.csv 
  amazon_data_dir: artifacts/data_ingestion/raw_data/AMZN.csv
  google_data_dir: artifacts/data_ingestion/raw_data/GOOG.csv
  microsoft_data_dir: artifacts/data_ingestion/raw_data/MSFT.csv
  transformed_apple_data_dir: artifacts/data_transformation/transformed_data/apple_data
  transformed_amazon_data_dir: artifacts/data_transformation/transformed_data/amazon_data
  transformed_google_data_dir: artifacts/data_transformation/transformed_data/google_data
  transformed_microsoft_data_dir: artifacts/data_transformation/transformed_data/microsoft_data
  